# Generated by Django 3.2.16 on 2025-04-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_auto_20250424_1334"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "verbose_name": "публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
    ]
